/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.model.Fila_Deslocamento;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FilaView extends javax.swing.JFrame {

    Fila_Deslocamento fila;

    /**
     * Creates new form FilaView
     */
    public FilaView() {
        initComponents();
        fila = new Fila_Deslocamento(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilaExercicio06 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldElemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldResultFila = new javax.swing.JTextField();
        jButtonStatusDaFila = new javax.swing.JButton();
        jButtonQuantElementos = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonRetirarElemento = new javax.swing.JButton();
        jButtoninserirElemento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Fila Exercicio 05 Deslocamento");
        setResizable(false);

        jLabel1.setText("Inserir o elemento:");

        jLabel2.setText("Resultado da manipulação da fila com deslocamento:");

        jButtonStatusDaFila.setText("Status da Fila");
        jButtonStatusDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusDaFilaActionPerformed(evt);
            }
        });

        jButtonQuantElementos.setText("Quant. Elementos");
        jButtonQuantElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuantElementosActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar o 1º da Fila");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonRetirarElemento.setText("Retirar Elemento");
        jButtonRetirarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarElementoActionPerformed(evt);
            }
        });

        jButtoninserirElemento.setText("Inserir Elemento");
        jButtoninserirElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninserirElementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilaExercicio06Layout = new javax.swing.GroupLayout(jPanelFilaExercicio06);
        jPanelFilaExercicio06.setLayout(jPanelFilaExercicio06Layout);
        jPanelFilaExercicio06Layout.setHorizontalGroup(
            jPanelFilaExercicio06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaExercicio06Layout.createSequentialGroup()
                .addGroup(jPanelFilaExercicio06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilaExercicio06Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFilaExercicio06Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jTextFieldElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilaExercicio06Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanelFilaExercicio06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldResultFila, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaExercicio06Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelFilaExercicio06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonQuantElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStatusDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtoninserirElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRetirarElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );
        jPanelFilaExercicio06Layout.setVerticalGroup(
            jPanelFilaExercicio06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaExercicio06Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldResultFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtoninserirElemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStatusDaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuantElementos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRetirarElemento)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaExercicio06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaExercicio06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoninserirElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninserirElementoActionPerformed
        // TODO add your handling code here:
        try {
            fila.enqueue(Integer.parseInt(jTextFieldElemento.getText()));
            jTextFieldResultFila.setText("Inserido um elemento!\n");
            jTextFieldElemento.setText("");
            jTextFieldElemento.requestFocus();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtoninserirElementoActionPerformed

    private void jButtonStatusDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            if (fila.isEmpty()) {
                jTextFieldResultFila.setText("A fila está vazia!\n");
            } else if (fila.isFull()) {
                jTextFieldResultFila.setText("A fila está cheia!\n");
            } else {
                jTextFieldResultFila.setText("A fila está com " + fila.size() + " elemento(s)");
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonStatusDaFilaActionPerformed

    private void jButtonQuantElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuantElementosActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultFila.setText("Quantidade de elementos na fila > " + fila.size());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonQuantElementosActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultFila.setText("O primeiro elemento da fila é > " + fila.peek() + ""
                    + " na posição > " + fila.getInicio());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonRetirarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarElementoActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultFila.setText("Retirando o elemento > " + fila.peek());
            fila.dequeue();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonRetirarElementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonQuantElementos;
    private javax.swing.JButton jButtonRetirarElemento;
    private javax.swing.JButton jButtonStatusDaFila;
    private javax.swing.JButton jButtoninserirElemento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelFilaExercicio06;
    private javax.swing.JTextField jTextFieldElemento;
    private javax.swing.JTextField jTextFieldResultFila;
    // End of variables declaration//GEN-END:variables
}
